# Generated by Django 3.1 on 2020-08-23 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_auther'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='auther',
            new_name='author',
        ),
    ]
